name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
        working-directory: ./wnfs-swift-pkg
      - name: Run tests
        run: swift test
        working-directory: ./wnfs-swift-pkg